name: flutter_yks_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pinch_zoom: ^1.0.0

  google_fonts: ^4.0.4
  modal_bottom_sheet: ^3.0.0-pre

  font_awesome_flutter: ^10.1.0

  flutter_svg: ^1.1.1+1

  provider: ^6.0.0

  uuid: ^3.0.5

  purchases_flutter: ^4.3.1

  image_cropper: ^3.0.0

  image_picker: ^0.8.4+2

  animations: ^2.0.2

  smooth_page_indicator: ^1.0.0+2

  sleek_circular_slider: ^2.0.1

  flutter_spinbox: ^0.11.0

  percent_indicator: ^4.2.2

  animate_do: ^3.0.2
  connectivity_plus: ^3.0.2

  cached_network_image: ^3.2.0

  hive: ^2.0.6
  hive_flutter: ^1.1.0

  awesome_dialog: ^3.0.2

  flutter_easyloading: ^3.0.3

  shimmer: ^2.0.0

  sliding_up_panel: ^2.0.0+1

  badges: ^2.0.2

  awesome_notifications: ^0.7.4+1

  animated_bottom_navigation_bar: ^1.0.1
  flutter_inset_box_shadow: ^1.0.8

  json_annotation: ^4.4.0
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.0.3
  firebase_auth: ^4.1.0

  crypto: ^3.0.1
  google_sign_in: ^5.2.4
  sign_in_with_apple: ^4.0.0
  firebase_performance: ^0.9.0+3
  firebase_analytics: ^10.0.3
  firebase_crashlytics: ^3.0.3
  firebase_messaging: ^14.0.3
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.1.4
  fl_chart: ^0.55.0
  confetti: ^0.7.0
  animated_text_kit: ^4.2.2
  flutter_lorem: ^2.0.0
  lottie: ^2.0.0
  carousel_slider: ^4.1.1
  firebase_in_app_messaging: ^0.7.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.5
  json_serializable: ^6.1.3

  flutter_lints: ^2.0.1

  flutter_native_splash: ^2.2.9

  hive_generator: ^2.0.0

  flutter_launcher_icons: ^0.11.0
  path_provider: ^2.0.11

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.jpg"

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo_name.png
  android: true
  ios: true

  android_12:
    image: assets/images/android_splash.png
    color: "#000000"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - .env

